language: go
dist: xenial
sudo: false
services: [docker]

matrix:
  include:
    - os: linux
      go: 1.14.x

before_deploy:
  - make dist

deploy:
  provider: releases
  api_key:
    secure: Qhweoc+1/wLjbq6uNUHti8ZSaFFhuYTrGLaUKVR/QMNJtIbIuEjIXYhPYdKOl67vId2SDjTYW9tsAEpYReWmpzRZ33uVke/G1tXovrGVZFiIxgytndDKintJzC1LKMWdy0k9X9CVIg5e1jd7DiJOKauwM4/y4quJiTgy1z66rkrYH/HIM3h47gDno74y7/8OSpgNcdYr5iashwWdT7eWE5Dn1Fr8v6+/ClLQpbxczB0la8cU3zQl+o8qvZ3Y5lNEBOcCV7FtFpXhFnYEDGtVpZBIUXFJLIRCj4+HQ0DqZ+wC4RGb7lSkRLvTqhpIPn2a4gIOkKXeS3J9dgBYXHkWYF+wLUmbtqgWW7a6jK2n1G8MFNrbQiLi+AgIcbop8h96Q1W8ueBYj7cMXlKKlWAX5PGt2zryvD4DR3P/iFhC6h1jf/ISVVl2BJUbLSCmzv+qR8Y41ptzWUR2lC3lR2/OCbEpgnU5AiZfPhJNrooKm4fHxTGH23d6HCWDw1NthYUMBkn22Jkf3pEZYQsGXj7Q00jgQ6WfAlbb7SHWgbxVb+fSgkU0tWtWInf76VZhROfdCqtvmkqJV3ThLi0RRzXi7CHilx9mL05ISkaDmoJWULDgUb5qdrIvg8Bhi/5EDWQ8sEDJEN239F7go1I6HPtD6P9BYXgS09tu8cidzF4mtyw=
  file_glob: true
  file:
    - bin/wire-*
  on:
    repo: moov-io/wire
    tags: true
    go: 1.14.x
  skip_cleanup: true

after_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make release-push

notifications:
  slack:
    secure: POMpq1kBtVB3z/7kzQtMq39V4ulipVzEoes90BsIHxV3aXcNP9PChdzJSacD7NlTLlq7xLV0xAs33rHxVGri2n3cuTaNTQO2CvXmRFVsfKhv30Lodkcn1OjBVlJPdUI1C4VBWjY047gapjtzeOuKspg2K4vKc9r3ZME9afPxIxjB5KrB1Hmnp4sIsxQ5avsttyUVWKQjNbpe2SgLzdn3Rbo3mSmf2MebGEhzD206LLVTJ06M/OiWzovJuArv3b6THfM0/UamqK2b+l1I6kHEd4snK5SIo4Oq8fB/dPKKeBsS7xxN8YHrHwvFAYqCCRzSMkILWGPxVlz3uWkcJ15P7cenW/bJ3245kYCOQtA+oVlzbN6S8oFqOYXSpxTOp2PfytTZ+2lnNcunj2Gwd0JIZA9Y/c4MKGgea7l1klFVebNVEHWXZThvo5XS+hmtUNxRID+Hl5nuIyK+RUyfTlOC+ptb3bb/jEmLCTshiGryNgPOwywDx57YCw4t1wEG0U9gi67py8h5DHzpK7mrxclPz568zQ7s2/uCgvAqbFQfI33MSulcTc+CX5PVFM4Cf9mBseQNvVNeAn0nmwzAt78sTBHig8CTLA8sX25By71xGQLh17edoRCDDq7BK8//rJGV3XpktWl1BDFDSioWjUGUPqzoNfhiuHENwbh0GMhsqUs=
